language: php

php:
  - 5.6

before_script:
  - composer selfupdate
  - composer install -n --prefer-dist

script:
  - ./bin/phpspec run
  - ./bin/phpunit --coverage-clover build/logs/clover.xml
  - ./bin/test-reporter

notifications:
  slack: donbstringham:uSrXFfUaMNvRj3I8tQHWDH1j
