language: php

php:
  - 5.6

before_script:
  - composer selfupdate
  - composer install -n --prefer-dist

script:
  - ./bin/phpspec run
  - ./bin/test-reporter --coverage-report="clover.xml"

notifications:
  slack: donbstringham:uSrXFfUaMNvRj3I8tQHWDH1j
