language: php

php:
  - 5.6

before_script:
  - composer install -n --prefer-dist

script:
  - ./bin/phpspec run

notifications:
  slack: donbstringham:4G7cilG3EnSG0vbQwlNcmcnd

addons:
    code_climate:
        repo_token: 2df93cbdea3ad7a63c4892eada5ffc2c0f13bc68073e2d1d315310ac418f1a90
